// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: example/api/service_two.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExampleServiceTwoClient is the client API for ExampleServiceTwo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleServiceTwoClient interface {
	Stats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type exampleServiceTwoClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleServiceTwoClient(cc grpc.ClientConnInterface) ExampleServiceTwoClient {
	return &exampleServiceTwoClient{cc}
}

func (c *exampleServiceTwoClient) Stats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.ExampleServiceTwo/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServiceTwoServer is the server API for ExampleServiceTwo service.
// All implementations must embed UnimplementedExampleServiceTwoServer
// for forward compatibility
type ExampleServiceTwoServer interface {
	Stats(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedExampleServiceTwoServer()
}

// UnimplementedExampleServiceTwoServer must be embedded to have forward compatible implementations.
type UnimplementedExampleServiceTwoServer struct {
}

func (UnimplementedExampleServiceTwoServer) Stats(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedExampleServiceTwoServer) mustEmbedUnimplementedExampleServiceTwoServer() {}

// UnsafeExampleServiceTwoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleServiceTwoServer will
// result in compilation errors.
type UnsafeExampleServiceTwoServer interface {
	mustEmbedUnimplementedExampleServiceTwoServer()
}

func RegisterExampleServiceTwoServer(s grpc.ServiceRegistrar, srv ExampleServiceTwoServer) {
	s.RegisterService(&ExampleServiceTwo_ServiceDesc, srv)
}

func _ExampleServiceTwo_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceTwoServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ExampleServiceTwo/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceTwoServer).Stats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ExampleServiceTwo_ServiceDesc is the grpc.ServiceDesc for ExampleServiceTwo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExampleServiceTwo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.ExampleServiceTwo",
	HandlerType: (*ExampleServiceTwoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stats",
			Handler:    _ExampleServiceTwo_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/service_two.proto",
}

// ExampleServiceThreeClient is the client API for ExampleServiceThree service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleServiceThreeClient interface {
	Stats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type exampleServiceThreeClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleServiceThreeClient(cc grpc.ClientConnInterface) ExampleServiceThreeClient {
	return &exampleServiceThreeClient{cc}
}

func (c *exampleServiceThreeClient) Stats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.ExampleServiceThree/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServiceThreeServer is the server API for ExampleServiceThree service.
// All implementations must embed UnimplementedExampleServiceThreeServer
// for forward compatibility
type ExampleServiceThreeServer interface {
	Stats(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedExampleServiceThreeServer()
}

// UnimplementedExampleServiceThreeServer must be embedded to have forward compatible implementations.
type UnimplementedExampleServiceThreeServer struct {
}

func (UnimplementedExampleServiceThreeServer) Stats(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedExampleServiceThreeServer) mustEmbedUnimplementedExampleServiceThreeServer() {}

// UnsafeExampleServiceThreeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleServiceThreeServer will
// result in compilation errors.
type UnsafeExampleServiceThreeServer interface {
	mustEmbedUnimplementedExampleServiceThreeServer()
}

func RegisterExampleServiceThreeServer(s grpc.ServiceRegistrar, srv ExampleServiceThreeServer) {
	s.RegisterService(&ExampleServiceThree_ServiceDesc, srv)
}

func _ExampleServiceThree_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceThreeServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ExampleServiceThree/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceThreeServer).Stats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ExampleServiceThree_ServiceDesc is the grpc.ServiceDesc for ExampleServiceThree service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExampleServiceThree_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.ExampleServiceThree",
	HandlerType: (*ExampleServiceThreeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stats",
			Handler:    _ExampleServiceThree_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/service_two.proto",
}
