// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/service_one.proto

package pb

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
)

var rbacService_ExampleServiceOne = rbac.Service{
	Name: "ExampleServiceOne",
	Rules: &rbac.Rules{
		AccessLevel: 1,
	},
	Methods: map[string]*rbac.Method{
		"example.ExampleServiceOne.Update": {
			Rules: &rbac.Rules{
				AccessLevel: 3,
				AllowedRoles: []string{
					"manager",
					"director",
				},
			},
		},
	},
}

func (UnimplementedExampleServiceOneServer) GetRBACService() *rbac.Service {
	return &rbacService_ExampleServiceOne
}
