// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/service_one.proto

package pb

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
)

var rbacExampleServiceOne = rbac.Service{
	Rules: &rbac.Rules{
		AccessLevel: 1,
	},
	Methods: map[string]*rbac.Method{
		"Update": {
			Rules: &rbac.Rules{
				AccessLevel: 3,
				AllowedRoles: []string{
					"manager",
					"director",
				},
			},
		},
	},
}

func (UnimplementedExampleServiceOneServer) CheckAccess(fullMethod string, roles []string) bool {
	return rbac.CheckAccess(&rbacExampleServiceOne, fullMethod, roles)
}
