// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/service.proto

package pb

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
	desc "github.com/casnerano/protoc-gen-go-rbac/proto"
)

var accessServices = map[string]rbac.AccessService{
	"ExampleService": {
		Rules: &rbac.AccessRules{
			AccessLevel: desc.AccessLevel_ACCESS_LEVEL_PUBLIC,
		},
		Methods: map[string]rbac.AccessMethod{
			"Update": {
				Rules: &rbac.AccessRules{
					AccessLevel: desc.AccessLevel_ACCESS_LEVEL_PRIVATE,
					AllowedRoles: []string{
						"manager",
						"director",
					},
				},
			},
		},
	},
}

func (UnimplementedExampleServiceServer) CheckRolesAccess(fullMethod string, roles []string) bool {
	return rbac.CheckRolesAccess(accessServices, fullMethod, roles)
}
