// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/service_two.proto

package pb

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
)

var rbacService_ExampleServiceTwo = rbac.Service{
	Name: "ExampleServiceTwo",
	Rules: &rbac.Rules{
		AccessLevel: 3,
	},
	Methods: map[string]*rbac.Method{},
}

func (UnimplementedExampleServiceTwoServer) GetRBACService() *rbac.Service {
	return &rbacService_ExampleServiceTwo
}

var rbacService_ExampleServiceThree = rbac.Service{
	Name:  "ExampleServiceThree",
	Rules: nil,
	Methods: map[string]*rbac.Method{
		"Stats": {
			Rules: &rbac.Rules{
				AccessLevel: 3,
				AllowedRoles: []string{
					"admin",
				},
			},
		},
	},
}

func (UnimplementedExampleServiceThreeServer) GetRBACService() *rbac.Service {
	return &rbacService_ExampleServiceThree
}
