// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/service.proto

package pb

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
	desc "github.com/casnerano/protoc-gen-go-rbac/proto"
)

var rbacExampleService = rbac.Service{
	Rules: &desc.Rules{
		AccessLevel: desc.AccessLevel_ACCESS_LEVEL_PUBLIC,
	},
	Methods: map[string]*rbac.Method{
		"Update": {
			Rules: &desc.Rules{
				AccessLevel: desc.AccessLevel_ACCESS_LEVEL_PRIVATE,
				AllowedRoles: []string{
					"manager",
					"director",
				},
			},
		},
	},
}

func (UnimplementedExampleServiceServer) CheckAccess(fullMethod string, roles []string) bool {
	return rbac.CheckAccess(&rbacExampleService, fullMethod, roles)
}

var rbacExampleServiceExt = rbac.Service{
	Rules: &desc.Rules{
		AccessLevel: desc.AccessLevel_ACCESS_LEVEL_PUBLIC,
	},
	Methods: map[string]*rbac.Method{},
}

func (UnimplementedExampleServiceExtServer) CheckAccess(fullMethod string, roles []string) bool {
	return rbac.CheckAccess(&rbacExampleServiceExt, fullMethod, roles)
}
