// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: example/api/service_one.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExampleServiceOneClient is the client API for ExampleServiceOne service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleServiceOneClient interface {
	Stats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Update(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type exampleServiceOneClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleServiceOneClient(cc grpc.ClientConnInterface) ExampleServiceOneClient {
	return &exampleServiceOneClient{cc}
}

func (c *exampleServiceOneClient) Stats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.ExampleServiceOne/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleServiceOneClient) Update(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.ExampleServiceOne/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServiceOneServer is the server API for ExampleServiceOne service.
// All implementations must embed UnimplementedExampleServiceOneServer
// for forward compatibility
type ExampleServiceOneServer interface {
	Stats(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	Update(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedExampleServiceOneServer()
}

// UnimplementedExampleServiceOneServer must be embedded to have forward compatible implementations.
type UnimplementedExampleServiceOneServer struct {
}

func (UnimplementedExampleServiceOneServer) Stats(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedExampleServiceOneServer) Update(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedExampleServiceOneServer) mustEmbedUnimplementedExampleServiceOneServer() {}

// UnsafeExampleServiceOneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleServiceOneServer will
// result in compilation errors.
type UnsafeExampleServiceOneServer interface {
	mustEmbedUnimplementedExampleServiceOneServer()
}

func RegisterExampleServiceOneServer(s grpc.ServiceRegistrar, srv ExampleServiceOneServer) {
	s.RegisterService(&ExampleServiceOne_ServiceDesc, srv)
}

func _ExampleServiceOne_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceOneServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ExampleServiceOne/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceOneServer).Stats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleServiceOne_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceOneServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ExampleServiceOne/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceOneServer).Update(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ExampleServiceOne_ServiceDesc is the grpc.ServiceDesc for ExampleServiceOne service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExampleServiceOne_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.ExampleServiceOne",
	HandlerType: (*ExampleServiceOneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stats",
			Handler:    _ExampleServiceOne_Stats_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ExampleServiceOne_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/service_one.proto",
}
