// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: example/api/service2.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExampleService2Client is the client API for ExampleService2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleService2Client interface {
	// Метод наследует правила сервиса.
	Stat(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Метод переопределяет уровень доступа сервиса,
	// и устанавливает его открытым для определенных ролей.
	Update(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type exampleService2Client struct {
	cc grpc.ClientConnInterface
}

func NewExampleService2Client(cc grpc.ClientConnInterface) ExampleService2Client {
	return &exampleService2Client{cc}
}

func (c *exampleService2Client) Stat(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.ExampleService2/Stat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleService2Client) Update(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/example.ExampleService2/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleService2Server is the server API for ExampleService2 service.
// All implementations must embed UnimplementedExampleService2Server
// for forward compatibility
type ExampleService2Server interface {
	// Метод наследует правила сервиса.
	Stat(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Метод переопределяет уровень доступа сервиса,
	// и устанавливает его открытым для определенных ролей.
	Update(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedExampleService2Server()
}

// UnimplementedExampleService2Server must be embedded to have forward compatible implementations.
type UnimplementedExampleService2Server struct {
}

func (UnimplementedExampleService2Server) Stat(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedExampleService2Server) Update(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedExampleService2Server) mustEmbedUnimplementedExampleService2Server() {}

// UnsafeExampleService2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleService2Server will
// result in compilation errors.
type UnsafeExampleService2Server interface {
	mustEmbedUnimplementedExampleService2Server()
}

func RegisterExampleService2Server(s grpc.ServiceRegistrar, srv ExampleService2Server) {
	s.RegisterService(&ExampleService2_ServiceDesc, srv)
}

func _ExampleService2_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleService2Server).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ExampleService2/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleService2Server).Stat(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleService2_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleService2Server).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ExampleService2/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleService2Server).Update(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ExampleService2_ServiceDesc is the grpc.ServiceDesc for ExampleService2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExampleService2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.ExampleService2",
	HandlerType: (*ExampleService2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stat",
			Handler:    _ExampleService2_Stat_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ExampleService2_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/api/service2.proto",
}
