// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/service2.proto

package pb

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
	desc "github.com/casnerano/protoc-gen-go-rbac/proto"
)

var rbacExampleService2 = rbac.Service{
	Rules: &desc.Rules{
		AccessLevel: desc.AccessLevel_ACCESS_LEVEL_PUBLIC,
	},
	Methods: map[string]*rbac.Method{},
}

func (UnimplementedExampleService2Server) CheckAccess(fullMethod string, roles []string) bool {
	return rbac.CheckAccess(&rbacExampleService2, fullMethod, roles)
}
