// Code generated by protoc-gen-go-rbac. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc (unknown)
// - protoc             (unknown)
// source: example/api/service_two.proto

package pb

import (
	"github.com/casnerano/protoc-gen-go-rbac/pkg/rbac"
	desc "github.com/casnerano/protoc-gen-go-rbac/proto"
)

var rbacExampleServiceTwo = rbac.Service{
	Rules: &desc.Rules{
		AccessLevel: desc.AccessLevel_ACCESS_LEVEL_PRIVATE,
	},
	Methods: map[string]*rbac.Method{},
}

func (UnimplementedExampleServiceTwoServer) CheckAccess(fullMethod string, roles []string) bool {
	return rbac.CheckAccess(&rbacExampleServiceTwo, fullMethod, roles)
}
